name: Publish beta release
on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    if: contains(fromJson('["mme", "ataibarkai"]'), github.actor)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run a command
        run: echo "This step runs only for whitelisted users."
